services:
  wiki-app:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
    environment:
      - NODE_ENV=development
    command: npm run dev
    stdin_open: true
    tty: true

  wiki-build:
    build: .
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
      - ./generate:/app/build-output
    environment:
      - NODE_ENV=production
    command: sh -c "npm run build && cp -r /app/out/* /app/build-output/ && echo 'Build completed successfully'"
    profiles:
      - build
