services:
  wiki-app:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
    environment:
      - NODE_ENV=development
    command: npm run dev
    stdin_open: true
    tty: true

  wiki-static:
    build: .
    ports:
      - "8080:80"
    environment:
      - NODE_ENV=production
