name: Build and Deploy

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main, develop ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm install
      
    - name: Run linter
      run: npm run lint
      continue-on-error: true
      
    - name: Build application
      id: build
      continue-on-error: true
      run: |
        echo "Starting build process..."
        echo "Current directory: $(pwd)"
        echo "Node version: $(node --version)"
        echo "NPM version: $(npm --version)"
        
        echo "Running npm run build..."
        npm run build
        echo "Build command completed"
        
        echo "Checking build output..."
        if [ -d "out" ]; then
          echo "out directory exists (static export)"
          ls -la out/
          echo "Build artifacts found"
          echo "build_success=true" >> $GITHUB_OUTPUT
        elif [ -d ".next" ]; then
          echo ".next directory exists (development build)"
          ls -la .next/
          echo "Build artifacts found"
          echo "build_success=true" >> $GITHUB_OUTPUT
        else
          echo "ERROR: No build output directory found"
          echo "Current directory contents:"
          ls -la
          echo "build_success=false" >> $GITHUB_OUTPUT
        fi
      
    - name: List build output
      run: |
        echo "=== Build output directory structure ==="
        ls -la
        echo "=== .next directory contents ==="
        ls -la .next/ || echo ".next directory not found"
        echo "=== out directory contents ==="
        ls -la out/ || echo "out directory not found"
      
    - name: Verify build artifacts
      run: |
        echo "Verifying build artifacts..."
        echo "Build success status: ${{ steps.build.outputs.build_success }}"
        if [ -d "out" ]; then
          echo "out directory exists (static export)"
          echo "Contents:"
          ls -la out/
          echo "File count: $(find out -type f | wc -l)"
        elif [ -d ".next" ]; then
          echo ".next directory exists (development build)"
          echo "Contents:"
          ls -la .next/
          echo "File count: $(find .next -type f | wc -l)"
        else
          echo "ERROR: No build output directory found"
          echo "Current directory contents:"
          ls -la
        fi
    
    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      if: steps.build.outputs.build_success == 'true'
      with:
        name: build-files
        path: out/
        if-no-files-found: warn
        retention-days: 7

  deploy:
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/main'
    permissions:
      contents: read
      pages: write
      id-token: write
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm install
      
    - name: Generate data
      run: npm run generate-data
      
    - name: Build application
      run: npm run build
      
    - name: Setup Pages
      uses: actions/configure-pages@v4
      
    - name: Upload artifact
      uses: actions/upload-pages-artifact@v3
      with:
        path: './out'
        
    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v4

